# Generated by Django 6.0.3 on 2026-03-29 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(choices=[(1, '1 orang'), (2, '2 orang'), (3, '3 orang'), (4, '4 orang'), (5, '5 orang'), (6, '6 orang'), (7, '7 orang'), (8, '8 orang'), (9, '9 orang'), (10, '10 orang'), (11, '11 orang'), (12, '12 orang')], default=4)),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('occupied', 'Terisi'), ('reserved', 'Dipesan'), ('unavailable', 'Tidak Tersedia')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tables/qr/')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['zone', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='🏢', max_length=10)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('pickup', 'Ambil Sendiri')], default='dine_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('zone', 'number')},
        ),
    ]
